---
pg_service: postgresql          # ou postgresql@14-main, conforme unit real
pg_port: 5432
pg_os_user: postgres
pg_psql_bin: psql
pg_expected_listen_addresses: "*"   # ou IP específico, ex.: "143.244.201.207"
pg_bind_external_check: true