---
# Configuração para PostgreSQL via Docker
pg_docker_container_name: "postgres"
pg_port: 5432
pg_bind_external_check: true

# O comando pg_isready roda dentro do container para validar a saúde do banco
pg_healthcheck_cmd: "pg_isready -U postgres" 