---
all:
  children:
    trino:
      hosts:
        madalena:
          ansible_host: 157.230.202.248
    postgres:
      hosts:
        goodview:
          ansible_host: 157.230.202.248
    mongo:
      hosts:
        goodview:
          ansible_host: 157.230.202.248