---
all:
  vars:
    ansible_user: fnadmin        # ← conexão global, independente de componente
  children:
    trino:
      hosts:
        madalena:
          ansible_host: 157.230.202.248
    trino_scripts:
      hosts:
        madalena:
          ansible_host: 157.230.202.248
    postgres:
      hosts:
        madalena:
          ansible_host: 157.230.202.248
    mongo:
      hosts:
        madalena:
          ansible_host: 157.230.202.248